# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  win: circleci/windows@2.3.0
jobs:
  build:
      executor: win/default
      steps:
      - checkout
      - run:
          name: Downloading Ngrok
          command: |
            Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
            Invoke-WebRequest https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.36-9754-beta/softether-vpnserver_vpnbridge-v4.36-9754-beta-2021.06.07-windows-x86_x64-intel.exe -OutFile softether-server.exe
      - run:
          name: Extracting Ngrok Files
          command: |
            Expand-Archive ngrok.zip
      - run:
          name: Connecting to your Ngrok account.
          command: |
            .\ngrok\ngrok.exe authtoken 1Q5yloOx951Skx1s5N2ngUpfp84_3c1XKF1SvphyViLZCqpWD
      - run:
          name: Activating RDP access.
          command: |
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
            Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
            Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
      - run:
          name: Check RDP Port
          command: |
            Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber"
      - run:
          name: Change RDP
          command: |
            Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber" -Value 7389
            New-NetFirewallRule -DisplayName 'RDPPORTLatest' -Profile 'Public' -Direction Inbound -Action Allow -Protocol TCP -LocalPort 7389 
            Restart-Service -Name "TermService" -Force -Verbose
      - run:
          name: Creating Tunnel Change
          command: |
            Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 7389"'
      - run:
          name: Connecting to your RDP
          command: cmd /c start.bat
      - run:
          name: RDP is ready
          command: ./loop.ps1