name: Basic

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: '10.15.1'
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.36-9754-beta/softether-vpnserver_vpnbridge-v4.36-9754-beta-2021.06.07-windows-x86_x64-intel.exe -OutFile softether-server.exe
        Invoke-WebRequest https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.36-9754-beta/softether-vpnclient-v4.36-9754-beta-2021.06.07-windows-x86_x64-intel.exe -OutFile softether-client.exe
        Invoke-WebRequest https://downloads.getfiddler.com/win/Fiddler%20Everywhere%202.0.0.exe -OutFile Fiddle.exe
        Invoke-WebRequest 'https://rustymitchell-my.sharepoint.com/:u:/g/personal/user1mitchell_thinhhuynh_cf/EYoHr8fkLsBPsvxHQkMVikMBip4sk1qL-kM14stglm2ijA?e=By5kV0&download=1' -OutFile softether-server.zip
        Invoke-WebRequest 'https://rustymitchell-my.sharepoint.com/:u:/g/personal/user1mitchell_thinhhuynh_cf/EQkXHPuF9YdMonEPBebfBCUBSCBCmiE5aRXJuC9yaVjkWw?e=sOHi4H&download=1' -OutFile softether-client.zip
        Invoke-WebRequest 'https://rustymitchell-my.sharepoint.com/:u:/g/personal/user1mitchell_thinhhuynh_cf/ESygxgRbY8VBl4BOHClsOYgBj00o_jwSYGOg-rw5HDrueg?e=XKAFZe&download=1' -OutFile Profile.pubxml
    - name: Extracting Ngrok Files.
      run: | 
        Expand-Archive ngrok.zip
        Expand-Archive softether-server.zip
        Expand-Archive softether-client.zip
    - name: Create Shotcut
      run: |
        tzutil /s "Central Standard Time"
        .\powershell\set-shortcut.ps1 "D:\a\First\First\softether-server\SoftEther VPN Server\vpnsmgr_x64.exe" "C:\Users\Public\Desktop\serve.lnk"
        .\powershell\set-shortcut.ps1 "D:\a\First\First\softether-client\SoftEther VPN Client\vpncmgr_x64.exe" "C:\Users\Public\Desktop\client.lnk"
        Invoke-WebRequest 'https://myexternalip.com/raw' | Select-Object -Expand Content
        Get-NetIPAddress -AddressFamily IPv4 | Format-Table
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        $env:NODE_OPTIONS="--max-old-space-size=8192"
    - name: Check RDP Port
      run:
        Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber"
    - name: Change RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber" -Value 7389
        New-NetFirewallRule -DisplayName 'RDPPORTLatest' -Profile 'Public' -Direction Inbound -Action Allow -Protocol TCP -LocalPort 7389 
        Restart-Service -Name "TermService" -Force -Verbose
    - name: Setup VPN
      run: |
        Start-Process -FilePath '.\softether-server\SoftEther VPN Server\vpnserver_x64.exe' -ArgumentList '/install'
        Start-Process -FilePath '.\softether-client\SoftEther VPN Client\vpnclient_x64.exe' -ArgumentList '/install'
    - name: Install soft
      run: |
        choco install vscode
        choco install procexp
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Creating Tunnel Change.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 7389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: RDP loop 1
      run: |
        .\powershell\loop.ps1
    - name: RDP loop 2
      run: |
        .\powershell\loop.ps1
    - name: RDP loop 3
      run: |
        .\powershell\loop.ps1