name: FreeRDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Node
      uses: actions/setup-node@v2
      with:
        node-version: '10.15.1'
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.36-9754-beta/softether-vpnserver_vpnbridge-v4.36-9754-beta-2021.06.07-windows-x86_x64-intel.exe -OutFile softether-server.exe
        Invoke-WebRequest https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases/download/v4.36-9754-beta/softether-vpnclient-v4.36-9754-beta-2021.06.07-windows-x86_x64-intel.exe -OutFile softether-client.exe
        Invoke-WebRequest https://downloads.getfiddler.com/win/Fiddler%20Everywhere%202.0.0.exe -OutFile Fiddle.exe
        Invoke-WebRequest 'https://rustymitchell-my.sharepoint.com/:u:/g/personal/user1mitchell_thinhhuynh_cf/EVXeq3c-QKxKtI1wSFo0jWgB2VR9RrjucYgYXk6xS-YT8Q?e=wiU4Cg&download=1' -OutFile softether-server.zip
        Invoke-WebRequest 'https://rustymitchell-my.sharepoint.com/:u:/g/personal/user1mitchell_thinhhuynh_cf/EQkXHPuF9YdMonEPBebfBCUBSCBCmiE5aRXJuC9yaVjkWw?e=sOHi4H&download=1' -OutFile softether-client.zip
        Invoke-WebRequest 'https://rustymitchell-my.sharepoint.com/:u:/g/personal/user1mitchell_thinhhuynh_cf/ESygxgRbY8VBl4BOHClsOYgBj00o_jwSYGOg-rw5HDrueg?e=XKAFZe&download=1' -OutFile Profile.pubxml
    - name: Extracting Ngrok Files.
      run: | 
        Expand-Archive ngrok.zip
        Expand-Archive softether-server.zip
        Expand-Archive softether-client.zip
    - name: Connecting to your Ngrok account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activating RDP access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Check RDP Port
      run:
        Get-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber"
    - name: Change RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "PortNumber" -Value 7389
        New-NetFirewallRule -DisplayName 'RDPPORTLatest' -Profile 'Public' -Direction Inbound -Action Allow -Protocol TCP -LocalPort 7389 
        Restart-Service -Name "TermService" -Force -Verbose
    - name: Active IIS.
      run: |
        Install-WindowsFeature -name Web-Server -IncludeManagementTools
        Install-WindowsFeature -name Web-FTP-Server,Web-Ftp-Ext -IncludeManagementTools
    - name: Firewal
      run: |
        netsh advfirewall firewall add rule name="FTP1" dir=in action=allow protocol=TCP localport=21,4000-5000 remoteport=any
        netsh advfirewall firewall add rule name="IIS1" dir=in action=allow protocol=TCP localport=5000-6000 remoteport=any
        netsh advfirewall set global StatefulFtp enable
        Restart-Service -Name "ftpsvc" -Force -Verbose
        .\SetACL.ps1
    - name: Show tree
      run: .\show-tree.ps1 '.' -MaxDepth 4
    - name: Setup VPN
      run: |
        Start-Process -FilePath '.\softether-server\SoftEther VPN Server\vpnserver_x64.exe' -ArgumentList '/install'
        Start-Process -FilePath '.\softether-client\SoftEther VPN Client\vpnclient_x64.exe' -ArgumentList '/install'
    - name: Install soft
      run: |
        choco install vscode
        choco install procexp
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Clone source
      run: |
        git clone -b $Env:BRANCH1 $Env:SRC1
      env:
        SRC1: ${{ secrets.SRC1 }}
        BRANCH1: ${{ secrets.BRANCH1 }}
    - name: Add Website
      run: |
        mkdir "D:\wasp"
        c:\Windows\System32\inetsrv\appcmd add site /name:"WASP" /bindings:"http/*:5183:,ftp/*:4183:" /physicalPath:"D:\wasp"
        c:\Windows\System32\inetsrv\appcmd set config -section:system.applicationHost/sites /[name='WASP'].ftpServer.security.authentication.anonymousAuthentication.enabled:true 
        c:\Windows\System32\inetsrv\appcmd set config -section:system.applicationHost/sites /[name='WASP'].ftpServer.security.authentication.basicAuthentication.enabled:true 
        c:\Windows\System32\inetsrv\appcmd set config -section:system.applicationHost/sites /[name='WASP'].ftpServer.security.ssl.controlChannelPolicy:"SslAllow" 
        c:\Windows\System32\inetsrv\appcmd set config -section:system.applicationHost/sites /[name='WASP'].ftpServer.security.ssl.dataChannelPolicy:"SslAllow" 
        c:\Windows\System32\inetsrv\appcmd set config -section:system.applicationHost/sites /[name='WASP'].ftpServer.directoryBrowse.showFlags:DisplayVirtualDirectories 
        c:\Windows\System32\inetsrv\appcmd set config -section:system.applicationHost/sites /[name='WASP'].ftpServer.userIsolation.mode:StartInUsersDirectory 
        c:\Windows\System32\inetsrv\appcmd set config WASP /section:system.ftpserver/security/authorization /+[accessType='Allow',permissions='Read',roles='',users='*'] /commit:apphost
      shell: cmd
    - name: Restore nuget
      run: |
        nuget.exe restore WASP.sln -source https://www.nuget.org/api/v2/
        nuget.exe restore WASP.sln -source https://nuget.fmgsuite.com/nuget/
      working-directory: wasp\src
    - name: Build
      run: |
        msbuild WASP.sln '/p:Configuration=DevSaiGon;DeployOnBuild=true;PublishProfile="D:\a\TestRepo\TestRepo\FolderProfile.pubxml"'
      working-directory: wasp\src
    - name: Creating Tunnel Change.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 7389"'
    - name: Connecting to your RDP.
      run: cmd /c start.bat
    - name: RDP is ready!
      run: |
        ./loop.ps1
